repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.13
      stages: [pre-commit]
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      stages: [pre-commit]
